import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pooja Enterprises",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  keywords: [
    "Pooja Enterprises",
    "Construction",
    "Building",
    "Architecture",
    "Design",
    "Projects",
    "Team",
  ],
  authors: [{ name: "Pooja Enterprises" }],
  creator: "Pooja Enterprises",
  publisher: "Pooja Enterprises",
  openGraph: {
    title: "Pooja Enterprises",
    description:
      "Building excellence through innovation and dedication since 1992.",
    url: "https://poojaenterprises.com",
    siteName: "Pooja Enterprises",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Pooja Enterprises - Building Excellence",
      },
    ],
    locale: "en_US",
    type: "website",
  },


  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-ET30S1XGFB"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-ET30S1XGFB');
        `}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
